// STATE_HINTS: 10 hints per state/FCT in fixed order.
// 1=Population range, 2=Economic activity, 3=Geography/terrain, 4=Cultural fact,
// 5=Famous artifact/history, 6=Nickname/slogan, 7=Region, 8=Directional position,
// 9=Letters in state name, 10=Capital city.
window.STATE_HINTS = {
  "Abia": [
    "Its population is under 5 million.",
    "Known for commerce and the Ariaria International Market; a hub for trade and manufacturing.",
    "Mostly lowland and tropical; one of the smaller states by area.",
    "Home to the Igbo; local dishes include Abacha and Ukwa; the Abiriba are famous traders.",
    "Aba was a key industrial centre; the area has a strong history of enterprise.",
    "Nickname: God's Own State.",
    "It is in the South-East.",
    "I am east of Rivers and south of Enugu.",
    "The state name has 4 letters.",
    "Its capital is Umuahia."
  ],
  "Adamawa": [
    "Population is over 4 million.",
    "Agriculture, livestock, and mining; a major trading and transport hub.",
    "Varied terrain: savannah, mountains near Cameroon, and the Benue valley.",
    "Hausa and Fulani; the Njuwa Fishing Festival; Lamido of Adamawa.",
    "Gashaka-Gumpti National Park; the American University of Nigeria is here.",
    "Known as the Land of Beauty.",
    "It is in the North-East.",
    "I am south of Borno and share a border with Cameroon.",
    "The state name has 7 letters.",
    "Its capital is Yola."
  ],
  "Akwa Ibom": [
    "Population is around 5 to 6 million.",
    "Major oil and gas producer; growing business and government centre.",
    "Coastal and riverine; mangrove and tropical rainforest near the Atlantic.",
    "Ibibio and Efik; Edikang ikong and Afang soup; the Ekpo masquerade.",
    "Ibom Plaza and Godswill Akpabio Stadium; the region had an early colonial port.",
    "Called the Land of Promise.",
    "It is in the South-South.",
    "I am south of Abia and east of Rivers.",
    "The state name has 8 letters (Akwa Ibom).",
    "Its capital is Uyo."
  ],
  "Anambra": [
    "Population is over 5 million.",
    "Commerce, Onitsha market, Nollywood; one of the most economically active states.",
    "Lowland and riverine; crossed by the Niger and dotted with marshes.",
    "Igbo; Ofe onugbu and Fio fio; the Ofala festival.",
    "Ogbunike Caves; Onitsha was a major river port; strong trading history.",
    "Nickname: Light of the Nation.",
    "It is in the South-East.",
    "I am south of Kogi and east of Delta.",
    "The state name has 7 letters.",
    "Its capital is Awka."
  ],
  "Bauchi": [
    "Population is over 6 million.",
    "Agriculture, livestock, and growing tourism around Yankari.",
    "Savannah and hills; Yankari Game Reserve and the Wikki Warm Springs.",
    "Hausa culture; Tuwo and Miyan kuka; the Durbar.",
    "Yankari Game Reserve; the Bauchi state history and the old Bauchi town.",
    "Known as the Pearl of Tourism.",
    "It is in the North-East.",
    "I am south of Kano and east of Kaduna.",
    "The state name has 6 letters.",
    "Its capital is Bauchi."
  ],
  "Bayelsa": [
    "Population is around 2 to 3 million.",
    "Oil and gas; fishing and palm produce; a major administrative and commercial hub.",
    "Mostly riverine, mangrove, and creeks; part of the Niger Delta.",
    "Ijaw; Banga soup and starch; boat regattas and water festivals.",
    "Heart of the Ijaw nation; key to the Niger Delta and oil history.",
    "Nickname: Glory of All Lands.",
    "It is in the South-South.",
    "I am south of Rivers and east of Delta.",
    "The state name has 7 letters.",
    "Its capital is Yenagoa."
  ],
  "Benue": [
    "Population is over 5 million.",
    "Agriculture: yam, rice, cassava; a major market and transport hub.",
    "Benue River valley; rolling plains and farmland.",
    "Tiv, Idoma, Igede; pounded yam and beniseed soup; the Akata fishing festival.",
    "Food basket of the nation; the Benue River; rich precolonial history.",
    "Called the Food Basket of the Nation.",
    "It is in the North-Central.",
    "I am south of Nasarawa and east of Kogi.",
    "The state name has 5 letters.",
    "Its capital is Makurdi."
  ],
  "Borno": [
    "Population is over 5 million.",
    "Trade, agriculture, and livestock; a major commercial centre in the North-East.",
    "Sahel and savannah; Lake Chad region; semi-arid in the north.",
    "Kanuri and Hausa; Tuwo and Dama; the Shehu of Borno; Islamic heritage.",
    "Kanem-Borno empire; Lake Chad; historic centre of Islamic learning.",
    "Known as the Home of Peace.",
    "It is in the North-East.",
    "I am north of Adamawa and east of Yobe.",
    "The state name has 5 letters.",
    "Its capital is Maiduguri."
  ],
  "Cross River": [
    "Population is around 4 million.",
    "Tourism, agriculture, and government; a key port and tourism hub.",
    "Coastal and rainforest; Obudu Plateau; the Cross River runs through it.",
    "Efik and Ejagham; Edikang ikong and Afang; a famous annual carnival.",
    "Obudu Cattle Ranch; an early colonial and slave trade port was here.",
    "Called the People's Paradise.",
    "It is in the South-South.",
    "I am south of Benue and east of Ebonyi.",
    "The state name has 10 letters (Cross River).",
    "Its capital is Calabar."
  ],
  "Delta": [
    "Population is over 5 million.",
    "Oil and gas, trade, and agriculture; home to a major port and commercial centres.",
    "Niger Delta; creeks, mangrove, and riverine; the Niger flows through.",
    "Urhobo, Itsekiri, Ijaw; Banga soup and starch; the Olotu festival.",
    "A major port and the state hub; key to the Niger Delta and oil industry.",
    "Nickname: the Big Heart.",
    "It is in the South-South.",
    "I am south of Anambra and west of Rivers.",
    "The state name has 5 letters.",
    "Its capital is Asaba."
  ],
  "Ebonyi": [
    "Population is under 4 million.",
    "Salt production, rice, and yam; a major market for the region.",
    "Inland and hilly; part of the Igbo heartland.",
    "Igbo; Okpa and Abacha; the Ijiagu festival.",
    "Created in 1996; known for salt and a famous local rice.",
    "Called the Salt of the Nation.",
    "It is in the South-East.",
    "I am south of Benue and east of Enugu.",
    "The state name has 6 letters.",
    "Its capital is Abakaliki."
  ],
  "Edo": [
    "Population is over 4 million.",
    "Government, commerce, and culture; a historic and business centre.",
    "Lowland and rainforest; crossed by rivers.",
    "Edo (Bini); pounded yam and Owo soup; the Igue festival and coral beads.",
    "Benin Kingdom; Benin Bronzes; the Oba of Benin; UNESCO heritage.",
    "Known as the Heartbeat of the Nation.",
    "It is in the South-South.",
    "I am south of Kogi and east of Ondo.",
    "The state name has 3 letters.",
    "Its capital is Benin City."
  ],
  "Ekiti": [
    "Population is around 3 million.",
    "Education and civil service; an administrative and educational hub.",
    "Rolling hills and valleys; Ikogosi Warm Springs; lush vegetation.",
    "Yoruba (Ekiti); pounded yam and eba; the Epa and Oloja Ogun festivals.",
    "Ikogosi Warm Springs; many tertiary institutions; fountain of knowledge.",
    "Called the Land of Honour and Integrity.",
    "It is in the South-West.",
    "I am north of Ondo and east of Osun.",
    "The state name has 5 letters.",
    "Its capital is Ado-Ekiti."
  ],
  "Enugu": [
    "Population is over 4 million.",
    "Coal heritage, commerce, and education; a major industrial and educational hub.",
    "Hilly; the Ngwo Pine Forest; coal-bearing uplands.",
    "Igbo; Ofe nsala and Abacha; the coal-mining heritage.",
    "Coal City; University of Nigeria Nsukka; former Eastern Region administrative seat.",
    "Nickname: the Coal City.",
    "It is in the South-East.",
    "I am north of Anambra and east of Kogi.",
    "The state name has 5 letters.",
    "Its capital is Enugu."
  ],
  "Federal Capital Territory": [
    "Population is over 3 million.",
    "Government, services, and diplomacy; the federal seat of power.",
    "Planned city; Aso Rock; savannah and hills.",
    "Diverse; Gbagyi and others; Tuwo and various cuisines; a major federal carnival.",
    "Aso Rock; National Assembly; Presidential Villa; built as the federal seat in the 1980s.",
    "The seat of Nigeria's federal government.",
    "It is in the North-Central.",
    "I am north of Kogi and south of Niger.",
    "The territory name has 25 letters (Federal Capital Territory).",
    "Its capital is Abuja."
  ],
  "Gombe": [
    "Population is over 3 million.",
    "Trade, agriculture, and transport; a regional commercial hub.",
    "Savannah; one of the smallest states by area.",
    "Hausa, Tangale, Waja; Tuwo and Fura da nono; the Dadiya culture.",
    "Created in 1996 from Bauchi; a key link in the North-East.",
    "Known as the Jewel in the Savannah.",
    "It is in the North-East.",
    "I am south of Borno and east of Bauchi.",
    "The state name has 5 letters.",
    "Its capital is Gombe."
  ],
  "Imo": [
    "Population is over 5 million.",
    "Commerce, oil, and education; a major commercial and educational hub.",
    "Lowland and riverine; Oguta Lake; tropical.",
    "Igbo; Ofe Owerri and Abacha; the Ahiajoku festival.",
    "Oguta Lake; Mbari culture; strong educational and commercial base.",
    "Called the Eastern Heartland.",
    "It is in the South-East.",
    "I am west of Abia and north of Rivers.",
    "The state name has 3 letters.",
    "Its capital is Owerri."
  ],
  "Jigawa": [
    "Population is over 5 million.",
    "Agriculture (rice, dates), livestock; a growing administrative and market hub.",
    "Sahel and savannah; Hadejia-Nguru wetlands.",
    "Hausa; Tuwo and Dambu; the Gwaram festival.",
    "Created in 1991 from Kano; a historic emirate and Birnin Kudu rocks.",
    "Known as the New World.",
    "It is in the North-West.",
    "I am east of Kano and north of Bauchi.",
    "The state name has 6 letters.",
    "Its capital is Dutse."
  ],
  "Kaduna": [
    "Population is over 8 million.",
    "Government, military, and education; a major political and educational hub.",
    "Savannah and hills; Kaduna River; diverse landscapes.",
    "Hausa, Gbagyi, and others; Tuwo and Masa; the Durbar.",
    "Nok culture; Ahmadu Bello University; historic university town and state history.",
    "Called the Centre of Learning.",
    "It is in the North-West.",
    "I am south of Katsina and west of Plateau.",
    "The state name has 6 letters.",
    "Its capital is Kaduna."
  ],
  "Kano": [
    "Population is over 14 million (one of the largest).",
    "Commerce, industry, and agriculture; one of the largest market cities in West Africa.",
    "Savannah; Dala Hill; semi-arid in the north.",
    "Hausa; Fura da nono; the Kurmi Market and dye pits; the Durbar.",
    "Ancient Kano; Kano Chronicle; Kano Emirate; historic trading centre.",
    "Known as the Centre of Commerce.",
    "It is in the North-West.",
    "I am north of Kaduna and west of Jigawa.",
    "The state name has 4 letters.",
    "Its capital is Kano."
  ],
  "Katsina": [
    "Population is over 8 million.",
    "Agriculture, trade, and traditional crafts; a major cultural and commercial hub.",
    "Savannah and semi-arid; Gobarau Minaret area.",
    "Hausa; Tuwo and Dambu; the Durbar; leatherwork and embroidery.",
    "Gobarau Minaret; Katsina Emirate; birthplace of many Nigerian leaders.",
    "Called the Home of Hospitality.",
    "It is in the North-West.",
    "I am north of Kaduna and east of Zamfara.",
    "The state name has 7 letters.",
    "Its capital is Katsina."
  ],
  "Kebbi": [
    "Population is over 4 million.",
    "Rice farming, fishing, and livestock; a major agricultural and fishing hub.",
    "Riverine and savannah; borders the Niger River.",
    "Hausa; Tuwo and Masa; the Argungu Fishing Festival.",
    "Argungu Fishing Festival; Kanta Museum; Yauri kingdom history.",
    "Known as the Land of Equity.",
    "It is in the North-West.",
    "I am south of Sokoto and west of Niger.",
    "The state name has 5 letters.",
    "Its capital is Birnin Kebbi."
  ],
  "Kogi": [
    "Population is over 4 million.",
    "Confluence of Niger and Benue; a historic and transport hub.",
    "Where the Niger and Benue meet; Mount Patti; varied terrain.",
    "Igala, Ebira, Okun (Yoruba); pounded yam and eba; the Ogani festival.",
    "The first colonial administrative capital of Nigeria was here; Lord Lugard House.",
    "Called the Confluence State.",
    "It is in the North-Central.",
    "I am south of the FCT and north of Anambra.",
    "The state name has 4 letters.",
    "Its capital is Lokoja."
  ],
  "Kwara": [
    "Population is over 3 million.",
    "Agriculture, education, and trade; a gateway between North and South.",
    "Savannah; Jebba Dam on the Niger; transition zone north–south.",
    "Yoruba, Nupe, Hausa; Amala and Eba; the Emir of Ilorin; Durbar.",
    "University of Ilorin; Jebba Hydroelectric Dam; gateway between North and South.",
    "Known as the State of Harmony.",
    "It is in the North-Central.",
    "I am south of Niger and north of Oyo.",
    "The state name has 5 letters.",
    "Its capital is Ilorin."
  ],
  "Lagos": [
    "Population is over 15 million (largest in Nigeria).",
    "Finance, port, entertainment (Nollywood), commerce; Nigeria's economic hub.",
    "Coastal; lagoons, islands, and Atlantic coast; small in area.",
    "Yoruba; jollof, amala, eba; the Eyo festival.",
    "Lagos port; National Theatre; former federal capital; Centre of Excellence.",
    "Nickname: the Centre of Excellence.",
    "It is in the South-West.",
    "I am south of Ogun and on the Atlantic coast.",
    "The state name has 5 letters.",
    "Its capital is Ikeja."
  ],
  "Nassarawa": [
    "Population is over 2 million.",
    "Solid minerals and agriculture; a growing mining and administrative hub.",
    "Hills and plains; Farin Ruwa Falls; borders the FCT.",
    "Eggon, Hausa, and others; Tuwo and pounded yam; the Aku festival.",
    "Tin mining; Farin Ruwa Falls; Nasarawa Emirate.",
    "Called the Home of Solid Minerals.",
    "It is in the North-Central.",
    "I am south of Plateau and east of the FCT.",
    "The state name has 9 letters.",
    "Its capital is Lafia."
  ],
  "Niger": [
    "Population is over 5 million.",
    "Hydropower (Kainji, Shiroro dams), agriculture; supplies much of Nigeria's electricity.",
    "Largest state by area; Gurara Falls; Zuma Rock; River Niger.",
    "Nupe, Hausa, Gbagyi; Tuwo and Daddawa; the Gani Festival.",
    "Kainji and Shiroro dams; Zuma Rock; Kainji National Park.",
    "Known as the Power State.",
    "It is in the North-Central.",
    "I am south of Kebbi and north of the FCT.",
    "The state name has 5 letters.",
    "Its capital is Minna."
  ],
  "Ogun": [
    "Population is over 5 million.",
    "Industry, commerce, and commuting to Lagos; a major industrial corridor.",
    "Rolling terrain; Olumo Rock; tropical.",
    "Yoruba (Egba); Amala and Eba; the Lisabi festival; Adire fabric.",
    "Olumo Rock; Obasanjo Presidential Library; Gateway State.",
    "Called the Gateway State.",
    "It is in the South-West.",
    "I am north of Lagos and east of the Republic of Benin.",
    "The state name has 4 letters.",
    "Its capital is Abeokuta."
  ],
  "Ondo": [
    "Population is over 4 million.",
    "Cocoa, government, and education; a major cocoa-producing and administrative hub.",
    "Coastal and forest; Idanre Hills; Ikogosi Warm Springs.",
    "Yoruba (Ondo); pounded yam and eba; the Ogun festival.",
    "Idanre Hills; Ikogosi Warm Springs; Owo Museum.",
    "Known as the Sunshine State.",
    "It is in the South-West.",
    "I am south of Ekiti and east of Ogun.",
    "The state name has 4 letters.",
    "Its capital is Akure."
  ],
  "Osun": [
    "Population is over 4 million.",
    "Tourism, culture, and education; home to a UNESCO Sacred Grove.",
    "Forest and sacred groves; Osun River; Osun-Osogbo Grove (UNESCO).",
    "Yoruba; Amala and Iyan; the Osun Osogbo festival.",
    "Osun-Osogbo Sacred Grove (UNESCO); goddess Osun; Yoruba art and culture.",
    "Called the State of the Living Spring.",
    "It is in the South-West.",
    "I am east of Oyo and north of Ondo.",
    "The state name has 4 letters.",
    "Its capital is Oshogbo."
  ],
  "Oyo": [
    "Population is over 7 million.",
    "Commerce, education, and agriculture; one of the largest cities in Africa by area.",
    "Savannah and forest; one of the largest cities (Ibadan) by area.",
    "Yoruba; Amala and Eba; the Alaafin of Oyo; Oke'badan festival.",
    "Old Oyo Empire; University of Ibadan; Cocoa House; Mapo Hall.",
    "Known as the Pace Setter.",
    "It is in the South-West.",
    "I am north of Ogun and west of Osun.",
    "The state name has 3 letters.",
    "Its capital is Ibadan."
  ],
  "Plateau": [
    "Population is over 4 million.",
    "Tourism, mining (tin historically), and agriculture; a cool-climate hub.",
    "Plateaus and hills; cool climate; Shere Hills; Riyom Rocks.",
    "Berom, Afizere, and others; pounded yam and Tuwo; the Nzem Berom festival.",
    "Jos Museum; Wildlife Park; tin mining history; Home of Peace and Tourism.",
    "Called the Home of Peace and Tourism.",
    "It is in the North-Central.",
    "I am north of Nasarawa and east of Bauchi.",
    "The state name has 7 letters.",
    "Its capital is Jos."
  ],
  "Rivers": [
    "Population is over 7 million.",
    "Oil and gas, port, and commerce; the heart of Nigeria's oil industry.",
    "Niger Delta; creeks, mangrove, and riverine.",
    "Ikwerre, Ijaw, and others; Banga soup and pepper soup.",
    "A major port and oil hub; Isaac Boro Park; Treasure Base of the Nation.",
    "Nickname: the Treasure Base of the Nation.",
    "It is in the South-South.",
    "I am south of Imo and east of Delta.",
    "The state name has 6 letters.",
    "Its capital is Port Harcourt."
  ],
  "Sokoto": [
    "Population is over 5 million.",
    "Trade, agriculture, and Islamic scholarship; the spiritual seat of Nigerian Muslims.",
    "Sahel and savannah; semi-arid.",
    "Hausa and Fulani; Tuwo and Fura; the Sultan of Sokoto; Durbar.",
    "Sokoto Caliphate; Sultan's Palace; Hubbaren Shehu; seat of the Caliphate.",
    "Known as the Seat of the Caliphate.",
    "It is in the North-West.",
    "I am north of Kebbi and west of Zamfara.",
    "The state name has 6 letters.",
    "Its capital is Sokoto."
  ],
  "Taraba": [
    "Population is around 3 to 4 million.",
    "Agriculture, tourism (Gashaka-Gumpti), and diverse trades; an ethnically diverse hub.",
    "Mambilla Plateau; Gashaka-Gumpti Park; rainforest and savannah; borders Cameroon.",
    "Jukun, Kuteb, Tiv, and others; pounded yam and Tuwo; the Nwonyo Fishing Festival.",
    "Gashaka-Gumpti National Park; Mambilla Plateau; Nature's Gift to the Nation.",
    "Known as Nature's Gift to the Nation.",
    "It is in the North-East.",
    "I am south of Gombe and east of Benue.",
    "The state name has 6 letters.",
    "Its capital is Jalingo."
  ],
  "Yobe": [
    "Population is over 3 million.",
    "Agriculture, livestock, and trade; a key hub in the North-East.",
    "Sahel; Nguru wetlands; semi-arid.",
    "Kanuri and Hausa; Tuwo and Fura; the Bade fishing festival.",
    "Dufuna Canoe (old canoe in Africa); Old Kanem-Borno heritage.",
    "Called the Pride of the Sahel.",
    "It is in the North-East.",
    "I am west of Borno and south of the Republic of Niger.",
    "The state name has 4 letters.",
    "Its capital is Damaturu."
  ],
  "Zamfara": [
    "Population is over 4 million.",
    "Gold mining, agriculture, and livestock; a mining and agricultural hub.",
    "Savannah and semi-arid; Zamfara River.",
    "Hausa; Tuwo and Dambu; traditional crafts.",
    "First state to introduce Sharia in Nigeria; Gusau Emirate; gold deposits.",
    "Known as the Farming Haven.",
    "It is in the North-West.",
    "I am south of Sokoto and east of Kebbi.",
    "The state name has 7 letters.",
    "Its capital is Gusau."
  ]
};
